### ISSUE TITLE
Needs Review

### ISSUE THREAD

**Issue by callumgillies** [UCLHp/pdd-analysis#2]
Please review my terrible code

**Comment by agosling** [comment]
I've reviewed the code but haven't run it as I don't have access at home.  Tests run, and otherwise the writing is good.  A couple of things that may help with navigation:

 - Perhaps adjust the names of the two files that contain sets of code that are only to be called by other programmes - call them module files or something like that.
 - For each of your main pieces of code you have defined a main() function.  I've not been using the name main() for any of my programmes so that even if it is designed to run on its own, if later I find I want to run it from another piece of code I can call it in just like any other package and reference it from within my code.

**Comment by callumgillies** [comment]
Thanks for taking a look :)

- I had changed the names from "module" to separate scripts that had a more descriptive title so that they sort of described what they were doing, this was from feedback from Steve and to me makes a bit more sense as long as the README blurb is clear enough for describing what each one does?
- You can still call it from elsewhere, but by using the main function this way, if you wanted to import a module or a class from within the code, but not have the whole thing run, that would be possible too.

If you're happy enough I might just go ahead and close the issue?

**Comment by agosling** [comment]
Cool!

Yeah, definitely go ahead and release.
